---
- hosts: ec2-lampservers
  vars:
    http_port: 80
    max_clients: 200
  remote_user: ec2-user
  become: yes
  tasks:
  - name: ensure apache is at the latest version
    yum: name=httpd24 state=latest
    notify:
    - restart apache
  - name: ensure apache is running (and enable it at boot)
    service: name=httpd state=started enabled=yes
  handlers:
    - name: restart apache
      service: name=httpd state=restarted