---
# ^^^ YAML documents must begin with the document separator "---"
#
#### Example docblock, I like to put a descriptive comment at the top of my 
#### playbooks.
#
# Overview: Playbook to create directory, upload private repo keys, deploy git project, seed database, and configure apache
# Applies to: SpireMedia AWS Linux AMIs
# Description: 
#   Uses variables from the pro-ject-vars.yaml companion file
#   Files to load on the server live in the conf/ subdirectory
###########
- hosts: datacenters
  vars_files:
    - project-vars.yaml
  gather_facts: true
  remote_user: ec2-user
  become: yes

  tasks:
  - name: Clean up any existing code.
    shell: rm -rf {{ project_root }}

  - name: Create the project directory.
    file: state=directory path={{ project_root }}

  - name: Update the project directory.
    file: group={{ www_user }} owner={{ www_user }} mode=755 state=directory path={{ project_root }}

  - name: Install apache configuration file.
    copy: src=conf/{{ project_name }}.conf dest=/etc/httpd/conf.d/{{ project_name }}.conf
    
  - name: Pull sources from the repository.
    git: repo={{ project_repo }} dest={{ project_root }} version={{ branch }}
   
  - name: push sql dump to server.
    copy: src=conf/{{ project_name }}.sql dest={{ project_root }}/{{ project_name }}.sql
    
  - name: Create database.
    shell: mysql -u {{ mysql_user }} -p{{ mysql_password }} {{ project_name }} < {{ project_root }}/{{ project_name }}.sql
    
  - name: Run composer update.
    shell: /usr/local/bin/composer --no-interaction --working-dir={{ project_root }} update
    
  - name: Change ownership.
    shell: chown -R {{ www_user }}:{{ www_user }} {{ project_root }}
  
  - name: Restart services.
    service: name=httpd state=restarted
  